/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class example */

#ifndef _Included_example
#define _Included_example
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     example
 * Method:    clusteringTest6
 * Signature: ([D[DD)D
 */
JNIEXPORT jdouble JNICALL Java_com_mindspree_days_engine_ClusterEngine_clusteringTest6
        (JNIEnv *, jclass, jdoubleArray, jdoubleArray, jdouble);

JNIEXPORT void JNICALL Java_com_mindspree_days_engine_ClusterEngine_clusteringTest6Initialize
        (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
