/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class example */

#ifndef _Included_example
#define _Included_example
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     example
 * Method:    clusteringTest6
 * Signature: ([D[DD)D
 */
JNIEXPORT jdouble JNICALL Java_com_ninethirty_picnpics_HelloJni_clusteringTest6
  (JNIEnv *, jclass, jdoubleArray, jdoubleArray, jdouble);

JNIEXPORT jdouble JNICALL Java_com_ninethirty_picnpics_HelloJni_clusteringTest6Initialize
        (JNIEnv *, jclass, jdoubleArray, jdoubleArray, jdouble);

#ifdef __cplusplus
}
#endif
#endif
